package org.practicatrim2

/**
 * Clase enumerada con una cierta cantidad de especies de suculentas.
 */
enum class EspeciesSuculentas() {
    ECHEVERIA_ELEGANS, ALOE_VERA, CRASSULA_OVATA, HAWORTHIA_ATTENUATA, SEDUM_MORGANIANUM, SEMPERVIVUM_TECTORUM,
    KALANCHOE_TOMENTOSA, GRAPTOPETALUM_PARAGUAYENSE, EUPHORBIA_TRIGONA, SENECIO_ROWLEYANUS, LITHOPS, PACHYPHYTUM_OVIFERUM,
    GASTERIA_BICOLOR, AEONIUM_ARBOREUM, AGAVE_AMERICANA;
}
